Coveralls ci
P33J3/CMS-NuKeys pull request #2
Opened 2022-05-01 21:17 UTC by P33J3

![coveralls](https://user-images.githubusercontent.com/81102471/166164758-f7b0e8d9-d1e3-4eae-9726-5d2d8c41c7e3.jpg)

screenshot showing a successful run of coverall

![screencapture-app-circleci-pipelines](https://user-images.githubusercontent.com/81102471/166164961-63850f75-204e-4632-b5e9-1789295dcd16.jpg)

screenshot showing a successful run of circle CI 

Notes:

I am not sure if the app was truly deployed to Heroku.

I am not sure how to update the coverage badge on Github.

2022-05-01 22:50 UTC, P33J3 commented
In last commit, i used https://circleci.com/developer/orbs/orb/coveralls/coveralls to try to push coverage from CircleCI to Coveralls. Code has been added to .circleci/config.yml

2022-05-02 00:19 UTC, Avuidrauxs requested changes
Awesome job putting together Coveralls and CircleCI, you seem to have a thing for DevOps 😅 . Resolve the critical comments before we proceed on this PR.

2022-05-02 00:19 UTC, Avuidrauxs commented on coverage/clover.xml
> +        <line num="40" count="1" type="stmt"/>
### Critical

Add the coverage directory to `.gitignore`

2022-05-02 00:19 UTC, Avuidrauxs commented on logs/all.log
> +2022-05-01 01:09:34:934 [35mhttp[39m: [35mGET /logger 304 - - 6.038 ms[39m
### Critical

Add the logs directory to `.gitignore`

2022-05-02 01:10 UTC, merged